name: build tiger
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - tiger/**
jobs:
  push:
    name: "tiger:${{ matrix.base }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base:
          - ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ocr-117
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./tiger/${{ matrix.base }}
          file: ./tiger/${{ matrix.base }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ocr-117/tiger:${{ matrix.base }}
